#!/usr/bin/env python3
"""
Combined Schedule Evaluator

This script evaluates the combined schedule generated by the combined scheduler.
It performs comprehensive analysis including:
1. LTP (Lecture-Tutorial-Practical) constraint verification
2. Theory-Lab conflict detection by semester/department
3. Group distribution visualization
4. Comprehensive constraint verification
"""

import os
import sys
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
from datetime import datetime
import glob

# Add parent directory to path for imports
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(os.path.dirname(current_dir))
sys.path.insert(0, parent_dir)

class CombinedScheduleEvaluator:
    def __init__(self, output_dir="output", analytics_dir="src/data_analytics/combined_analytics"):
        self.output_dir = output_dir
        self.analytics_dir = analytics_dir
        self.create_analytics_directory()
        
        # Time mappings
        self.theory_slots = [
            "8:00 - 8:50", "9:00 - 9:50", "10:00 - 10:50", "11:00 - 11:50",
            "12:00 - 12:50", "1:00 - 1:50", "2:00 - 2:50", "3:00 - 3:50", 
            "4:00 - 4:50", "5:00 - 5:50", "6:00 - 6:50"
        ]
        
        self.lab_sessions = {
            'L1': {'time_range': '8:00 - 9:40', 'slots': ['8:00 - 8:50', '8:50 - 9:40']},
            'L2': {'time_range': '9:50 - 11:30', 'slots': ['9:50 - 10:40', '10:40 - 11:30']},
            'L3': {'time_range': '11:50 - 1:30', 'slots': ['11:50 - 12:40', '12:40 - 1:30']},
            'L4': {'time_range': '1:50 - 3:30', 'slots': ['1:50 - 2:40', '2:40 - 3:30']},
            'L5': {'time_range': '3:50 - 5:30', 'slots': ['3:50 - 4:40', '4:40 - 5:30']},
            'L6': {'time_range': '5:30 - 7:10', 'slots': ['5:30 - 6:20', '6:20 - 7:10']}
        }
        
        self.days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
        
    def create_analytics_directory(self):
        """Create the analytics directory structure."""
        os.makedirs(self.analytics_dir, exist_ok=True)
        
        # Create subdirectories
        subdirs = ['reports', 'visualizations', 'conflict_analysis', 'group_distributions']
        for subdir in subdirs:
            os.makedirs(os.path.join(self.analytics_dir, subdir), exist_ok=True)
    
    def find_latest_combined_schedule(self):
        """Find the most recent combined schedule output."""
        combined_dirs = sorted(glob.glob(os.path.join(self.output_dir, 'combined_schedule_*')), reverse=True)
        
        if not combined_dirs:
            print("❌ No combined schedule directories found!")
            return None, None, None
        
        latest_dir = combined_dirs[0]
        print(f"📁 Using latest combined schedule: {latest_dir}")
        
        # Look for CSV files
        lab_csv = os.path.join(latest_dir, 'combined_lab_schedule.csv')
        theory_csv = os.path.join(latest_dir, 'combined_theory_schedule.csv')
        course_file = None
        
        # Try to find the course file used
        possible_course_files = [
            'data/department_data/Computing_department.csv'
        ]
        
        for course_path in possible_course_files:
            if os.path.exists(course_path):
                course_file = course_path
                break
        
        return lab_csv, theory_csv, course_file
    
    def load_schedule_data(self):
        """Load the combined schedule data."""
        lab_csv, theory_csv, course_file = self.find_latest_combined_schedule()
        
        if not lab_csv or not theory_csv:
            print("❌ Could not find combined schedule files!")
            return None
        
        data = {}
        
        # Load lab schedule
        if os.path.exists(lab_csv):
            data['lab_schedule'] = pd.read_csv(lab_csv)
            print(f"✅ Loaded lab schedule: {len(data['lab_schedule'])} assignments")
        else:
            print(f"❌ Lab schedule not found: {lab_csv}")
            return None
        
        # Load theory schedule
        if os.path.exists(theory_csv):
            data['theory_schedule'] = pd.read_csv(theory_csv)
            print(f"✅ Loaded theory schedule: {len(data['theory_schedule'])} assignments")
        else:
            print(f"❌ Theory schedule not found: {theory_csv}")
            return None
        
        # Load course requirements
        if course_file and os.path.exists(course_file):
            data['course_requirements'] = pd.read_csv(course_file)
            print(f"✅ Loaded course requirements: {len(data['course_requirements'])} courses")
        else:
            print(f"⚠️ Course file not found: {course_file}")
            data['course_requirements'] = None
        
        return data
    
    def verify_ltp_constraints(self, data):
        """Verify Lecture-Tutorial-Practical constraints."""
        print("\n" + "="*80)
        print("🔍 LTP CONSTRAINT VERIFICATION")
        print("="*80)
        
        violations = []
        
        if data['course_requirements'] is None:
            print("❌ Cannot verify LTP constraints without course requirements")
            return {'success': False, 'violations': ['Missing course requirements']}
        
        # Create mapping of course requirements
        course_requirements = {}
        for _, row in data['course_requirements'].iterrows():
            instance_id = str(row['id'])
            course_requirements[instance_id] = {
                'lecture_hours': row['lecture_hours'],
                'practical_hours': row['practical_hours'],
                'tutorial_hours': row['tutorial_hours'],
                'course_code': row['course_code'],
                'course_name': row['course_name'],
                'teacher_id': row['teacher_id'],
                'student_count': row['student_count']
            }
        
        # Count scheduled hours per course instance
        scheduled_hours = defaultdict(lambda: {'lecture': 0, 'tutorial': 0, 'practical': 0})
        
        # Count theory assignments
        for _, row in data['theory_schedule'].iterrows():
            instance_id = str(row['course_instance_id'])
            session_type = row.get('session_type', 'lecture').lower()
            
            if session_type in ['lecture', 'theory']:
                scheduled_hours[instance_id]['lecture'] += 1
            elif session_type in ['tutorial', 'tut']:
                scheduled_hours[instance_id]['tutorial'] += 1
        
        # Count lab assignments (each lab session = 2 practical hours)
        for _, row in data['lab_schedule'].iterrows():
            instance_id = str(row['course_instance_id'])
            scheduled_hours[instance_id]['practical'] += 2
        
        # Verify constraints for each course
        compliant_courses = 0
        total_courses = 0
        
        print(f"{'ID':<6} {'Course':<12} {'L Req':<5} {'L Sch':<5} {'T Req':<5} {'T Sch':<5} {'P Req':<5} {'P Sch':<5} {'Status':<15}")
        print("-" * 85)
        
        for instance_id, requirements in course_requirements.items():
            total_courses += 1
            
            lecture_required = requirements['lecture_hours']
            tutorial_required = requirements['tutorial_hours']
            practical_required = requirements['practical_hours']
            
            lecture_scheduled = scheduled_hours[instance_id]['lecture']
            tutorial_scheduled = scheduled_hours[instance_id]['tutorial']
            practical_scheduled = scheduled_hours[instance_id]['practical']
            
            # Check compliance
            lecture_ok = lecture_scheduled >= lecture_required
            tutorial_ok = tutorial_scheduled >= tutorial_required
            practical_ok = practical_scheduled >= practical_required
            
            if lecture_ok and tutorial_ok and practical_ok:
                status = "✅ COMPLIANT"
                compliant_courses += 1
            else:
                status = "❌ VIOLATION"
                
                if not lecture_ok:
                    violations.append(f"Course {requirements['course_code']} (ID: {instance_id}): "
                                    f"Lecture shortage - need {lecture_required}, got {lecture_scheduled}")
                if not tutorial_ok:
                    violations.append(f"Course {requirements['course_code']} (ID: {instance_id}): "
                                    f"Tutorial shortage - need {tutorial_required}, got {tutorial_scheduled}")
                if not practical_ok:
                    violations.append(f"Course {requirements['course_code']} (ID: {instance_id}): "
                                    f"Practical shortage - need {practical_required}, got {practical_scheduled}")
            
            print(f"{instance_id:<6} {requirements['course_code']:<12} {lecture_required:<5} {lecture_scheduled:<5} "
                  f"{tutorial_required:<5} {tutorial_scheduled:<5} {practical_required:<5} {practical_scheduled:<5} {status:<15}")
        
        print("-" * 85)
        compliance_rate = (compliant_courses / total_courses) * 100 if total_courses > 0 else 0
        print(f"Compliance Rate: {compliant_courses}/{total_courses} ({compliance_rate:.1f}%)")
        
        # Save report
        report_path = os.path.join(self.analytics_dir, 'reports', 'ltp_constraints_report.txt')
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("LTP CONSTRAINT VERIFICATION REPORT\n")
            f.write("="*50 + "\n\n")
            f.write(f"Total Courses: {total_courses}\n")
            f.write(f"Compliant Courses: {compliant_courses}\n")
            f.write(f"Compliance Rate: {compliance_rate:.1f}%\n\n")
            f.write("VIOLATIONS:\n")
            for violation in violations:
                f.write(f"- {violation}\n")
        
        return {
            'success': len(violations) == 0,
            'compliance_rate': compliance_rate,
            'violations': violations,
            'total_courses': total_courses,
            'compliant_courses': compliant_courses
        }
    
    def verify_theory_lab_conflicts(self, data):
        """Verify that theory and lab groups don't conflict within same dept/semester."""
        print("\n" + "="*80)
        print("🔄 THEORY-LAB CONFLICT VERIFICATION")
        print("="*80)
        
        conflicts = []
        
        # Group theory sessions by department and semester
        theory_by_dept_sem = defaultdict(lambda: defaultdict(list))
        for _, session in data['theory_schedule'].iterrows():
            dept = session.get('department', 'Unknown')
            semester = session.get('semester', 0)
            group_index = session.get('group_index', 0)
            
            theory_by_dept_sem[dept][semester].append(session)
        
        # Group lab sessions by department and semester
        lab_by_dept_sem = defaultdict(lambda: defaultdict(list))
        for _, session in data['lab_schedule'].iterrows():
            dept = session.get('department', 'Unknown')
            semester = session.get('semester', 0)
            group_index = session.get('group_index', 0)
            
            lab_by_dept_sem[dept][semester].append(session)
        
        # Check for conflicts in each department-semester combination
        total_dept_sem = 0
        conflicted_dept_sem = 0
        
        for dept in set(list(theory_by_dept_sem.keys()) + list(lab_by_dept_sem.keys())):
            for semester in set(list(theory_by_dept_sem[dept].keys()) + list(lab_by_dept_sem[dept].keys())):
                if semester == 0 or dept == 'Unknown':
                    continue
                
                theory_sessions = theory_by_dept_sem[dept][semester]
                lab_sessions = lab_by_dept_sem[dept][semester]
                
                if not theory_sessions or not lab_sessions:
                    continue
                
                total_dept_sem += 1
                print(f"📋 Checking {dept} Semester {semester}:")
                print(f"   Theory sessions: {len(theory_sessions)}")
                print(f"   Lab sessions: {len(lab_sessions)}")
                
                # Check for time conflicts
                dept_conflicts = self._check_time_conflicts(theory_sessions, lab_sessions, dept, semester)
                if dept_conflicts:
                    conflicts.extend(dept_conflicts)
                    conflicted_dept_sem += 1
                    print(f"   ❌ Found {len(dept_conflicts)} conflicts")
                else:
                    print(f"   ✅ No conflicts")
        
        # Save conflict report
        report_path = os.path.join(self.analytics_dir, 'conflict_analysis', 'theory_lab_conflicts.txt')
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("THEORY-LAB CONFLICT ANALYSIS REPORT\n")
            f.write("="*50 + "\n\n")
            f.write(f"Total Department-Semester combinations checked: {total_dept_sem}\n")
            f.write(f"Combinations with conflicts: {conflicted_dept_sem}\n")
            f.write(f"Total conflicts found: {len(conflicts)}\n\n")
            f.write("CONFLICTS:\n")
            for conflict in conflicts:
                f.write(f"- {conflict}\n")
        
        print(f"\nConflict Summary: {len(conflicts)} conflicts in {conflicted_dept_sem}/{total_dept_sem} dept-sem combinations")
        
        return {
            'success': len(conflicts) == 0,
            'total_conflicts': len(conflicts),
            'conflicted_dept_sem': conflicted_dept_sem,
            'total_dept_sem': total_dept_sem,
            'conflicts': conflicts
        }
    
    def _check_time_conflicts(self, theory_sessions, lab_sessions, dept, semester):
        """Check for time conflicts between theory and lab sessions."""
        conflicts = []
        
        def parse_time_range(time_str):
            """Parse time range to start and end minutes."""
            try:
                start_str, end_str = time_str.split(' - ')
                
                def time_to_minutes(time_part):
                    hour, minute = map(int, time_part.split(':'))
                    return hour * 60 + minute
                
                return time_to_minutes(start_str), time_to_minutes(end_str)
            except:
                return None, None
        
        def time_ranges_overlap(start1, end1, start2, end2):
            """Check if two time ranges overlap."""
            if None in [start1, end1, start2, end2]:
                return False
            return start1 < end2 and start2 < end1
        
        # Check each theory session against each lab session
        for theory_session in theory_sessions:
            theory_day = theory_session.get('day')
            theory_timeslot = theory_session.get('time_slot', '')
            theory_group = theory_session.get('group_index', 0)
            
            for lab_session in lab_sessions:
                lab_day = lab_session.get('day')
                lab_session_name = lab_session.get('session_name', '')
                lab_group = lab_session.get('group_index', 0)
                
                # Only check sessions on the same day
                if theory_day == lab_day and theory_group == lab_group:
                    # Get theory time range
                    theory_start, theory_end = parse_time_range(theory_timeslot)
                    
                    # Get lab time range
                    if lab_session_name in self.lab_sessions:
                        lab_time_range = self.lab_sessions[lab_session_name]['time_range']
                        lab_start, lab_end = parse_time_range(lab_time_range)
                        
                        # Check for overlap
                        if time_ranges_overlap(theory_start, theory_end, lab_start, lab_end):
                            conflicts.append(
                                f"{dept} S{semester} G{theory_group}: Theory ({theory_timeslot}) "
                                f"conflicts with Lab {lab_session_name} ({lab_time_range}) on {theory_day}"
                            )
        
        return conflicts
    
    def generate_group_distributions(self, data):
        """Generate group distribution visualizations."""
        print("\n" + "="*80)
        print("📊 GENERATING GROUP DISTRIBUTION VISUALIZATIONS")
        print("="*80)
        
        viz_dir = os.path.join(self.analytics_dir, 'group_distributions')
        
        # Generate theory group distributions
        self._create_theory_group_visualizations(data['theory_schedule'], viz_dir)
        
        # Generate lab group distributions
        self._create_lab_group_visualizations(data['lab_schedule'], viz_dir)
        
        # Generate combined visualizations
        self._create_combined_group_visualizations(data, viz_dir)
        
        print(f"✅ Group distribution visualizations saved to {viz_dir}")
    
    def _create_theory_group_visualizations(self, theory_schedule, viz_dir):
        """Create theory group distribution visualizations."""
        # Group by department and semester
        dept_sem_groups = defaultdict(lambda: defaultdict(list))
        
        for _, session in theory_schedule.iterrows():
            dept = session.get('department', 'Unknown')
            semester = session.get('semester', 0)
            group_index = session.get('group_index', 0)
            
            if semester > 0 and dept != 'Unknown':
                group_key = f"G{group_index}"
                dept_sem_groups[(dept, semester)][group_key].append(session)
        
        # Create visualizations for each department-semester
        for (dept, semester), groups in dept_sem_groups.items():
            self._create_timetable_visualization(
                groups, f"Theory Groups - {dept} Semester {semester}",
                os.path.join(viz_dir, f"theory_{dept}_S{semester}.png"),
                is_theory=True
            )
    
    def _create_lab_group_visualizations(self, lab_schedule, viz_dir):
        """Create lab group distribution visualizations."""
        # Group by department and semester
        dept_sem_groups = defaultdict(lambda: defaultdict(list))
        
        for _, session in lab_schedule.iterrows():
            dept = session.get('department', 'Unknown')
            semester = session.get('semester', 0)
            group_index = session.get('group_index', 0)
            
            if semester > 0 and dept != 'Unknown':
                group_key = f"G{group_index}"
                dept_sem_groups[(dept, semester)][group_key].append(session)
        
        # Create visualizations for each department-semester
        for (dept, semester), groups in dept_sem_groups.items():
            self._create_timetable_visualization(
                groups, f"Lab Groups - {dept} Semester {semester}",
                os.path.join(viz_dir, f"lab_{dept}_S{semester}.png"),
                is_theory=False
            )
    
    def _create_combined_group_visualizations(self, data, viz_dir):
        """Create combined theory and lab group visualizations."""
        # This will create side-by-side visualizations showing both theory and lab groups
        pass  # Implementation would be similar to the individual visualizations
    
    def _create_timetable_visualization(self, groups, title, filename, is_theory=True):
        """Create a timetable visualization for group distributions."""
        plt.figure(figsize=(12, 8))
        
        # Create a matrix for the timetable
        num_days = len(self.days)
        num_slots = len(self.theory_slots) if is_theory else len(self.lab_sessions)
        
        # Initialize matrix
        timetable_matrix = np.zeros((num_slots, num_days))
        
        # Fill the matrix
        for group_name, sessions in groups.items():
            group_number = int(group_name[1:]) if group_name.startswith('G') else 1
            
            for _, session in enumerate(sessions):
                day = session.get('day')
                
                if day in self.days:
                    day_idx = self.days.index(day)
                    
                    if is_theory:
                        time_slot = session.get('time_slot', '')
                        if time_slot in self.theory_slots:
                            slot_idx = self.theory_slots.index(time_slot)
                            timetable_matrix[slot_idx, day_idx] = group_number
                    else:
                        session_name = session.get('session_name', '')
                        if session_name in self.lab_sessions:
                            slot_idx = list(self.lab_sessions.keys()).index(session_name)
                            timetable_matrix[slot_idx, day_idx] = group_number
        
        # Create the visualization
        im = plt.imshow(timetable_matrix, cmap='Set3', aspect='auto')
        
        plt.title(title, fontsize=14, fontweight='bold')
        plt.xlabel('Day')
        plt.ylabel('Time Slot')
        
        # Set labels
        plt.xticks(range(num_days), self.days, rotation=45)
        
        if is_theory:
            plt.yticks(range(num_slots), self.theory_slots)
        else:
            lab_labels = [f"{k} ({v['time_range']})" for k, v in self.lab_sessions.items()]
            plt.yticks(range(num_slots), lab_labels)
        
        # Add colorbar
        cbar = plt.colorbar(im)
        cbar.set_label('Group Number')
        
        plt.tight_layout()
        plt.savefig(filename, dpi=150, bbox_inches='tight')
        plt.close()
    
    def generate_comprehensive_report(self, ltp_results, conflict_results):
        """Generate a comprehensive evaluation report."""
        print("\n" + "="*80)
        print("📋 GENERATING COMPREHENSIVE EVALUATION REPORT")
        print("="*80)
        
        report_path = os.path.join(self.analytics_dir, 'reports', 'comprehensive_evaluation.txt')
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("COMBINED SCHEDULE COMPREHENSIVE EVALUATION REPORT\n")
            f.write("=" * 60 + "\n")
            f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            
            # LTP Constraints Section
            f.write("1. LTP CONSTRAINT VERIFICATION\n")
            f.write("-" * 30 + "\n")
            f.write(f"Status: {'✅ PASSED' if ltp_results['success'] else '❌ FAILED'}\n")
            f.write(f"Compliance Rate: {ltp_results['compliance_rate']:.1f}%\n")
            f.write(f"Total Courses: {ltp_results['total_courses']}\n")
            f.write(f"Compliant Courses: {ltp_results['compliant_courses']}\n")
            f.write(f"Violations: {len(ltp_results['violations'])}\n\n")
            
            # Theory-Lab Conflicts Section
            f.write("2. THEORY-LAB CONFLICT VERIFICATION\n")
            f.write("-" * 30 + "\n")
            f.write(f"Status: {'✅ PASSED' if conflict_results['success'] else '❌ FAILED'}\n")
            f.write(f"Total Conflicts: {conflict_results['total_conflicts']}\n")
            f.write(f"Conflicted Dept-Sem: {conflict_results['conflicted_dept_sem']}\n")
            f.write(f"Total Dept-Sem: {conflict_results['total_dept_sem']}\n\n")
            
            # Overall Assessment
            f.write("3. OVERALL ASSESSMENT\n")
            f.write("-" * 30 + "\n")
            overall_success = ltp_results['success'] and conflict_results['success']
            f.write(f"Overall Status: {'✅ PASSED' if overall_success else '❌ FAILED'}\n")
            
            if not overall_success:
                f.write("\nISSUES FOUND:\n")
                if not ltp_results['success']:
                    f.write("- LTP constraint violations detected\n")
                if not conflict_results['success']:
                    f.write("- Theory-lab conflicts detected\n")
            
            f.write(f"\nRecommendations:\n")
            if ltp_results['compliance_rate'] < 100:
                f.write("- Review course hour allocations\n")
            if conflict_results['total_conflicts'] > 0:
                f.write("- Resolve group scheduling conflicts\n")
        
        print(f"✅ Comprehensive report saved to {report_path}")
        
        return overall_success
    
    def run_evaluation(self):
        """Run the complete evaluation process."""
        print("🚀 STARTING COMBINED SCHEDULE EVALUATION")
        print("=" * 80)
        
        # Load data
        data = self.load_schedule_data()
        if not data:
            print("❌ Failed to load schedule data")
            return False
        
        # Run evaluations
        ltp_results = self.verify_ltp_constraints(data)
        conflict_results = self.verify_theory_lab_conflicts(data)
        
        # Generate visualizations
        self.generate_group_distributions(data)
        
        # Generate comprehensive report
        overall_success = self.generate_comprehensive_report(ltp_results, conflict_results)
        
        print("\n" + "="*80)
        print(f"🎯 EVALUATION COMPLETE: {'✅ PASSED' if overall_success else '❌ FAILED'}")
        print("="*80)
        print(f"📁 Results saved to: {self.analytics_dir}")
        
        return overall_success

def main():
    """Main function."""
    evaluator = CombinedScheduleEvaluator()
    success = evaluator.run_evaluation()
    return 0 if success else 1

if __name__ == "__main__":
    exit(main()) 