"""
app/models/analytics.py
========================
Reporting & Analytics module ORM model.

Table
-----
analytics_snapshots     — point-in-time export payload (for CSV/PDF reports).

Materialized views (workload_metrics, room_utilization) are NOT ORM models —
they are created via raw SQL in the Alembic migration and refreshed by a Celery
periodic beat task. They are read at the API layer using raw SELECT queries.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class AnalyticsSnapshot(Base):
    """
    Immutable point-in-time analytics export for a term.

    Generated by the Celery analytics task; consumed by the reporting API
    to serve cached CSV/PDF downloads without re-querying live tables.
    """

    __tablename__ = "analytics_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    institution_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    # Loose reference to the academic term; no FK so snapshots survive term deletion.
    academic_term_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    # Loose reference to the scenario whose output this snapshot reflects.
    # NULL means the snapshot covers the full term (all scenarios combined).
    # No FK — snapshots are immutable history; scenario deletion must not wipe them.
    scenario_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True, index=True
    )

    # Full serialised export payload — shape defined by AnalyticsSnapshotSchema.
    # Includes workload_metrics + room_utilization arrays at generation time.
    snapshot_data: Mapped[dict] = mapped_column(JSON, nullable=False)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    def __repr__(self) -> str:
        return (
            f"<AnalyticsSnapshot institution={self.institution_id}"
            f" term={self.academic_term_id} at={self.generated_at}>"
        )
