"""
app/db/migrations/
==================
Alembic migration scripts directory.

  env.py          → Alembic env configuration (auto-generated by `alembic init`).
  versions/       → Individual migration revision files.

Run migrations:
    alembic upgrade head
    alembic revision --autogenerate -m "description"
"""
